"""Fused GatedRMSNorm region implementations."""

from .rules import GATED_RMS_NORM_PATTERN, GATED_RMS_NORM_PROVENANCE
from .variants import (
    FUSED_GATED_RMS_NORM_DEFAULT,
    FUSED_GATED_RMS_NORM_FLA,
    FUSED_GATED_RMS_NORM_HUB_FLA,
    FUSED_GATED_RMS_NORM_REFERENCE,
    GATED_RMS_NORM_REGIONS,
)

__all__ = [
    "FUSED_GATED_RMS_NORM_DEFAULT",
    "FUSED_GATED_RMS_NORM_FLA",
    "FUSED_GATED_RMS_NORM_HUB_FLA",
    "FUSED_GATED_RMS_NORM_REFERENCE",
    "GATED_RMS_NORM_PATTERN",
    "GATED_RMS_NORM_PROVENANCE",
    "GATED_RMS_NORM_REGIONS",
]
