"""Fused RMSNorm region implementations."""

from .rules import RMSNORM_PATTERN, RMSNORM_PROVENANCE
from .variants import (
    FUSED_RMSNORM_HUB_MPS,
    FUSED_RMSNORM_HUB_XPU,
    FUSED_RMSNORM_LIGER,
    FUSED_RMSNORM_REFERENCE,
    RMSNORM_REGIONS,
)

__all__ = [
    "FUSED_RMSNORM_HUB_MPS",
    "FUSED_RMSNORM_HUB_XPU",
    "FUSED_RMSNORM_LIGER",
    "FUSED_RMSNORM_REFERENCE",
    "RMSNORM_PATTERN",
    "RMSNORM_PROVENANCE",
    "RMSNORM_REGIONS",
]
