"""Fused GatedDeltaNet block region implementations."""

from .rules import GATED_DELTA_NET_PATTERN, GATED_DELTA_NET_PROVENANCE
from .variants import (
    FUSED_GATED_DELTA_NET_COMPOSED_TIER_A,
    FUSED_GATED_DELTA_NET_DECODE,
    FUSED_GATED_DELTA_NET_FLA_LAYER_PARITY,
    GATED_DELTA_NET_REGIONS,
)

__all__ = [
    "FUSED_GATED_DELTA_NET_COMPOSED_TIER_A",
    "FUSED_GATED_DELTA_NET_DECODE",
    "FUSED_GATED_DELTA_NET_FLA_LAYER_PARITY",
    "GATED_DELTA_NET_PATTERN",
    "GATED_DELTA_NET_PROVENANCE",
    "GATED_DELTA_NET_REGIONS",
]
