"""Fused masked-softmax region implementations."""

from .rules import (
    MASKED_SOFTMAX_OP_SEQUENCES,
    MASKED_SOFTMAX_PATTERN,
    MASKED_SOFTMAX_PROVENANCE,
    MASKED_SOFTMAX_SINK_OP_SEQUENCES,
    MASKED_SOFTMAX_SINK_PATTERN,
)
from .variants import (
    FUSED_MASKED_SOFTMAX_MEGATRON,
    FUSED_MASKED_SOFTMAX_REFERENCE,
    FUSED_MASKED_SOFTMAX_SINK,
    FUSED_MASKED_SOFTMAX_TE,
    MASKED_SOFTMAX_REGIONS,
)

__all__ = [
    "FUSED_MASKED_SOFTMAX_MEGATRON",
    "FUSED_MASKED_SOFTMAX_REFERENCE",
    "FUSED_MASKED_SOFTMAX_SINK",
    "FUSED_MASKED_SOFTMAX_TE",
    "MASKED_SOFTMAX_OP_SEQUENCES",
    "MASKED_SOFTMAX_PATTERN",
    "MASKED_SOFTMAX_PROVENANCE",
    "MASKED_SOFTMAX_SINK_OP_SEQUENCES",
    "MASKED_SOFTMAX_SINK_PATTERN",
    "MASKED_SOFTMAX_REGIONS",
]
