"""Fused region lowering implementations."""

from .linear import FUSED_LINEAR_REGION
from .layernorm import FUSED_LAYERNORM_REGION
from .relu import RELU_REGION
from .rmsnorm import (
    FUSED_RMSNORM_HUB_MPS,
    FUSED_RMSNORM_HUB_XPU,
    FUSED_RMSNORM_LIGER,
    FUSED_RMSNORM_REFERENCE,
    RMSNORM_REGIONS,
)
from .masked_softmax import (
    FUSED_MASKED_SOFTMAX_MEGATRON,
    FUSED_MASKED_SOFTMAX_REFERENCE,
    FUSED_MASKED_SOFTMAX_TE,
    MASKED_SOFTMAX_PATTERN,
    MASKED_SOFTMAX_PROVENANCE,
    MASKED_SOFTMAX_REGIONS,
)
from .softmax import (
    FUSED_SOFTMAX_CUDA,
    FUSED_SOFTMAX_REFERENCE,
    SOFTMAX_PATTERN,
    SOFTMAX_PATTERN_SCALED,
    SOFTMAX_PROVENANCE,
    SOFTMAX_REGIONS,
)
from .xielu import (
    FUSED_XIELU_CUDA,
    FUSED_XIELU_REFERENCE,
    XIELU_REGIONS,
)

__all__ = [
    "FUSED_LAYERNORM_REGION",
    "FUSED_LINEAR_REGION",
    "FUSED_MASKED_SOFTMAX_MEGATRON",
    "FUSED_MASKED_SOFTMAX_REFERENCE",
    "FUSED_MASKED_SOFTMAX_TE",
    "FUSED_RMSNORM_HUB_MPS",
    "FUSED_RMSNORM_HUB_XPU",
    "FUSED_RMSNORM_LIGER",
    "FUSED_RMSNORM_REFERENCE",
    "FUSED_SOFTMAX_CUDA",
    "FUSED_SOFTMAX_REFERENCE",
    "FUSED_XIELU_CUDA",
    "FUSED_XIELU_REFERENCE",
    "MASKED_SOFTMAX_PATTERN",
    "MASKED_SOFTMAX_PROVENANCE",
    "MASKED_SOFTMAX_REGIONS",
    "RELU_REGION",
    "RMSNORM_REGIONS",
    "SOFTMAX_PATTERN",
    "SOFTMAX_PATTERN_SCALED",
    "SOFTMAX_PROVENANCE",
    "SOFTMAX_REGIONS",
    "XIELU_REGIONS",
]
