"""Fused region lowering implementations."""

from .gelu import (
    FUSED_GELU_ERF,
    FUSED_GELU_TANH,
    GELU_ERF_PATTERN,
    GELU_ERF_PROVENANCE,
    GELU_REGIONS,
    GELU_TANH_PATTERN,
    GELU_TANH_PROVENANCE,
)
from .gqa import (
    FUSED_GQA_FLASH2,
    FUSED_GQA_FLASH3,
    GQA_PATTERN,
    GQA_REGIONS,
)
from .linear import FUSED_LINEAR_REGION
from .linear_ce import (
    FUSED_LINEAR_CE_HUB_TRL,
    FUSED_LINEAR_CE_LIGER,
    FUSED_LINEAR_CE_REFERENCE,
    LINEAR_CE_PATTERN,
    LINEAR_CE_PROVENANCE,
    LINEAR_CE_REGIONS,
)
from .layernorm import FUSED_LAYERNORM_REGION
from .relu import RELU_REGION, RELU_REGIONS, RELU_SAVED_INPUT
from .silu import FUSED_SILU_REGION, SILU_REGIONS
from .squared_relu import (
    FUSED_SQUARED_RELU_REGION,
    SQUARED_RELU_PATTERN,
    SQUARED_RELU_REGIONS,
)
from .rmsnorm import (
    FUSED_RMSNORM_HUB_MPS,
    FUSED_RMSNORM_HUB_XPU,
    FUSED_RMSNORM_LIGER,
    FUSED_RMSNORM_REFERENCE,
    RMSNORM_REGIONS,
)
from .masked_softmax import (
    FUSED_MASKED_SOFTMAX_MEGATRON,
    FUSED_MASKED_SOFTMAX_REFERENCE,
    FUSED_MASKED_SOFTMAX_TE,
    MASKED_SOFTMAX_PATTERN,
    MASKED_SOFTMAX_PROVENANCE,
    MASKED_SOFTMAX_REGIONS,
)
from .softmax import (
    FUSED_SOFTMAX_CUDA,
    FUSED_SOFTMAX_REFERENCE,
    SOFTMAX_PATTERN,
    SOFTMAX_PATTERN_SCALED,
    SOFTMAX_PROVENANCE,
    SOFTMAX_REGIONS,
)
from .softplus import (
    FUSED_SOFTPLUS,
    FUSED_SOFTPLUS_SCALAR,
    SOFTPLUS_PATTERN,
    SOFTPLUS_PROVENANCE,
    SOFTPLUS_REGIONS,
)
from .xielu import (
    FUSED_XIELU_CUDA,
    FUSED_XIELU_REFERENCE,
    XIELU_REGIONS,
)

__all__ = [
    "FUSED_GELU_ERF",
    "FUSED_GELU_TANH",
    "FUSED_GQA_FLASH2",
    "FUSED_GQA_FLASH3",
    "FUSED_LAYERNORM_REGION",
    "FUSED_LINEAR_CE_HUB_TRL",
    "FUSED_LINEAR_CE_LIGER",
    "FUSED_LINEAR_CE_REFERENCE",
    "LINEAR_CE_PATTERN",
    "LINEAR_CE_PROVENANCE",
    "LINEAR_CE_REGIONS",
    "FUSED_LINEAR_REGION",
    "GELU_ERF_PATTERN",
    "GELU_ERF_PROVENANCE",
    "GELU_REGIONS",
    "GELU_TANH_PATTERN",
    "GELU_TANH_PROVENANCE",
    "GQA_PATTERN",
    "GQA_REGIONS",
    "FUSED_MASKED_SOFTMAX_MEGATRON",
    "FUSED_MASKED_SOFTMAX_REFERENCE",
    "FUSED_MASKED_SOFTMAX_TE",
    "FUSED_RMSNORM_HUB_MPS",
    "FUSED_RMSNORM_HUB_XPU",
    "FUSED_RMSNORM_LIGER",
    "FUSED_RMSNORM_REFERENCE",
    "FUSED_SOFTMAX_CUDA",
    "FUSED_SOFTMAX_REFERENCE",
    "FUSED_XIELU_CUDA",
    "FUSED_XIELU_REFERENCE",
    "MASKED_SOFTMAX_PATTERN",
    "MASKED_SOFTMAX_PROVENANCE",
    "MASKED_SOFTMAX_REGIONS",
    "RELU_REGION",
    "RELU_REGIONS",
    "RELU_SAVED_INPUT",
    "FUSED_SILU_REGION",
    "RMSNORM_REGIONS",
    "SILU_REGIONS",
    "FUSED_SQUARED_RELU_REGION",
    "SQUARED_RELU_PATTERN",
    "SQUARED_RELU_REGIONS",
    "SOFTMAX_PATTERN",
    "SOFTMAX_PATTERN_SCALED",
    "SOFTMAX_PROVENANCE",
    "FUSED_SOFTPLUS",
    "FUSED_SOFTPLUS_SCALAR",
    "SOFTPLUS_PATTERN",
    "SOFTPLUS_PROVENANCE",
    "SOFTPLUS_REGIONS",
    "SOFTMAX_REGIONS",
    "XIELU_REGIONS",
]
