"""Fused region lowering implementations."""

from .gelu import (
    FUSED_GELU_ERF,
    FUSED_GELU_TANH,
    GELU_ERF_PATTERN,
    GELU_ERF_PROVENANCE,
    GELU_REGIONS,
    GELU_TANH_PATTERN,
    GELU_TANH_PROVENANCE,
)
from .geglu import (
    FUSED_GEGLU_DECOMPOSED,
    FUSED_GEGLU_DECOMPOSED_ERF,
    FUSED_GEGLU_LIGER,
    GEGLU_ERF_PATTERN,
    GEGLU_PATTERN,
    GEGLU_PROVENANCE,
    GEGLU_REGIONS,
)
from .gqa import (
    FUSED_GQA_FLASH2,
    FUSED_GQA_FLASH3,
    GQA_PATTERN,
    GQA_REGIONS,
)
from .gqa_sink import (
    FUSED_GQA_SINK_FLASH2,
    FUSED_GQA_SINK_FLASH3,
    GQA_SINK_PATTERN,
    GQA_SINK_REGIONS,
)
from .linear import FUSED_LINEAR_REGION
from .linear_ce import (
    FUSED_LINEAR_CE_HUB_TRL,
    FUSED_LINEAR_CE_LIGER,
    FUSED_LINEAR_CE_REFERENCE,
    LINEAR_CE_PATTERN,
    LINEAR_CE_PROVENANCE,
    LINEAR_CE_REGIONS,
)
from .linear_ce_softcap import (
    FUSED_LINEAR_CE_SOFTCAP_HUB_TRL,
    FUSED_LINEAR_CE_SOFTCAP_LIGER,
    FUSED_LINEAR_CE_SOFTCAP_REFERENCE,
    LINEAR_CE_SOFTCAP_PATTERN,
    LINEAR_CE_SOFTCAP_PROVENANCE,
    LINEAR_CE_SOFTCAP_REGIONS,
)
from .depthwise_causal_conv1d import (
    DEPTHWISE_CAUSAL_CONV1D_REGIONS,
    FUSED_DEPTHWISE_CAUSAL_CONV1D_CUDA,
    FUSED_DEPTHWISE_CAUSAL_CONV1D_DECOMPOSED,
    FUSED_DEPTHWISE_CAUSAL_CONV1D_HUB,
)
from .gated_delta_net import (
    FUSED_GATED_DELTA_NET_COMPOSED_TIER_A,
    FUSED_GATED_DELTA_NET_DECODE,
    FUSED_GATED_DELTA_NET_FLA_LAYER_PARITY,
    GATED_DELTA_NET_REGIONS,
)
from .gated_delta_scan import (
    FUSED_GATED_DELTA_SCAN_DECODE,
    FUSED_GATED_DELTA_SCAN_FLA_CHUNK,
    FUSED_GATED_DELTA_SCAN_REFERENCE,
    GATED_DELTA_SCAN_REGIONS,
)
from .mamba2_scan import (
    FUSED_MAMBA2_SCAN_DECODE,
    FUSED_MAMBA2_SCAN_REFERENCE,
    FUSED_MAMBA2_SCAN_SSD_CHUNK,
    MAMBA2_SCAN_REGIONS,
)
from .gated_grouped_rms_norm import (
    FUSED_GATED_GROUPED_RMS_NORM_DEFAULT,
    FUSED_GATED_GROUPED_RMS_NORM_EAGER_HF,
    FUSED_GATED_GROUPED_RMS_NORM_REFERENCE,
    GATED_GROUPED_RMS_NORM_REGIONS,
)
from .gated_rms_norm import (
    FUSED_GATED_RMS_NORM_DEFAULT,
    FUSED_GATED_RMS_NORM_FLA,
    FUSED_GATED_RMS_NORM_HUB_FLA,
    FUSED_GATED_RMS_NORM_REFERENCE,
    GATED_RMS_NORM_REGIONS,
)
from .l2_normalize import (
    FUSED_L2_NORMALIZE_FLA,
    FUSED_L2_NORMALIZE_REFERENCE,
    L2_NORMALIZE_REGIONS,
)
from .logit_soft_cap import (
    FUSED_LOGIT_SOFT_CAP_REFERENCE,
    LOGIT_SOFT_CAP_REGIONS,
)
from .layernorm import FUSED_LAYERNORM_REGION
from .relu import RELU_REGION, RELU_REGIONS, RELU_SAVED_INPUT
from .silu import FUSED_SILU_REGION, SILU_REGIONS
from .squared_relu import (
    FUSED_SQUARED_RELU_REGION,
    SQUARED_RELU_PATTERN,
    SQUARED_RELU_REGIONS,
)
from .rmsnorm import (
    FUSED_RMSNORM_HUB_MPS,
    FUSED_RMSNORM_HUB_XPU,
    FUSED_RMSNORM_LIGER,
    FUSED_RMSNORM_REFERENCE,
    RMSNORM_REGIONS,
)
from .masked_softmax import (
    FUSED_MASKED_SOFTMAX_MEGATRON,
    FUSED_MASKED_SOFTMAX_REFERENCE,
    FUSED_MASKED_SOFTMAX_SINK,
    FUSED_MASKED_SOFTMAX_TE,
    MASKED_SOFTMAX_PATTERN,
    MASKED_SOFTMAX_PROVENANCE,
    MASKED_SOFTMAX_REGIONS,
    MASKED_SOFTMAX_SINK_PATTERN,
)
from .softmax_one import (
    FUSED_SOFTMAX_ONE_MEGATRON,
    FUSED_SOFTMAX_ONE_REFERENCE,
    SOFTMAX_ONE_PATTERN,
    SOFTMAX_ONE_PROVENANCE,
    SOFTMAX_ONE_REGIONS,
)
from .softmax import (
    FUSED_SOFTMAX_CUDA,
    FUSED_SOFTMAX_REFERENCE,
    SOFTMAX_PATTERN,
    SOFTMAX_PATTERN_SCALED,
    SOFTMAX_PROVENANCE,
    SOFTMAX_REGIONS,
)
from .swiglu import (
    FUSED_SWIGLU_DECOMPOSED,
    FUSED_SWIGLU_LIGER,
    FUSED_SWIGLU_LIGER_FUSED_GATE_UP,
    SWIGLU_PATTERN,
    SWIGLU_PROVENANCE,
    SWIGLU_REGIONS,
)
from .softplus import (
    FUSED_SOFTPLUS,
    FUSED_SOFTPLUS_SCALAR,
    SOFTPLUS_PATTERN,
    SOFTPLUS_PROVENANCE,
    SOFTPLUS_REGIONS,
)
from .xielu import (
    FUSED_XIELU_CUDA,
    FUSED_XIELU_REFERENCE,
    XIELU_REGIONS,
)
from .mamba2_mixer import (
    FUSED_MAMBA2_MIXER_COMPOSED_TIER_A,
    FUSED_MAMBA2_MIXER_DECODE,
    FUSED_MAMBA2_MIXER_HUB_MEGA,
    MAMBA2_MIXER_REGIONS,
)
from .rope_apply import ROPE_APPLY_REFERENCE, ROPE_APPLY_REGIONS
from .rope_materialize import (
    ROPE_MATERIALIZE_REFERENCE,
    ROPE_MATERIALIZE_REGIONS,
)

__all__ = [
    "FUSED_GEGLU_DECOMPOSED",
    "FUSED_GEGLU_DECOMPOSED_ERF",
    "FUSED_GEGLU_LIGER",
    "FUSED_GELU_ERF",
    "FUSED_GELU_TANH",
    "FUSED_GQA_FLASH2",
    "FUSED_GQA_FLASH3",
    "DEPTHWISE_CAUSAL_CONV1D_REGIONS",
    "FUSED_DEPTHWISE_CAUSAL_CONV1D_CUDA",
    "FUSED_DEPTHWISE_CAUSAL_CONV1D_DECOMPOSED",
    "FUSED_DEPTHWISE_CAUSAL_CONV1D_HUB",
    "FUSED_GATED_DELTA_NET_COMPOSED_TIER_A",
    "FUSED_GATED_DELTA_NET_DECODE",
    "FUSED_GATED_DELTA_NET_FLA_LAYER_PARITY",
    "GATED_DELTA_NET_REGIONS",
    "FUSED_GATED_DELTA_SCAN_DECODE",
    "FUSED_GATED_DELTA_SCAN_FLA_CHUNK",
    "FUSED_GATED_DELTA_SCAN_REFERENCE",
    "GATED_DELTA_SCAN_REGIONS",
    "FUSED_MAMBA2_SCAN_DECODE",
    "FUSED_MAMBA2_SCAN_REFERENCE",
    "FUSED_MAMBA2_SCAN_SSD_CHUNK",
    "MAMBA2_SCAN_REGIONS",
    "FUSED_GATED_GROUPED_RMS_NORM_DEFAULT",
    "FUSED_GATED_GROUPED_RMS_NORM_EAGER_HF",
    "FUSED_GATED_GROUPED_RMS_NORM_REFERENCE",
    "GATED_GROUPED_RMS_NORM_REGIONS",
    "FUSED_GATED_RMS_NORM_DEFAULT",
    "FUSED_GATED_RMS_NORM_FLA",
    "FUSED_GATED_RMS_NORM_HUB_FLA",
    "FUSED_GATED_RMS_NORM_REFERENCE",
    "GATED_RMS_NORM_REGIONS",
    "FUSED_L2_NORMALIZE_FLA",
    "FUSED_L2_NORMALIZE_REFERENCE",
    "FUSED_LAYERNORM_REGION",
    "FUSED_LINEAR_CE_HUB_TRL",
    "FUSED_LINEAR_CE_LIGER",
    "FUSED_LINEAR_CE_REFERENCE",
    "LINEAR_CE_PATTERN",
    "LINEAR_CE_PROVENANCE",
    "L2_NORMALIZE_REGIONS",
    "FUSED_LOGIT_SOFT_CAP_REFERENCE",
    "LOGIT_SOFT_CAP_REGIONS",
    "LINEAR_CE_REGIONS",
    "FUSED_LINEAR_CE_SOFTCAP_HUB_TRL",
    "FUSED_LINEAR_CE_SOFTCAP_LIGER",
    "FUSED_LINEAR_CE_SOFTCAP_REFERENCE",
    "LINEAR_CE_SOFTCAP_PATTERN",
    "LINEAR_CE_SOFTCAP_PROVENANCE",
    "LINEAR_CE_SOFTCAP_REGIONS",
    "FUSED_LINEAR_REGION",
    "GEGLU_ERF_PATTERN",
    "GEGLU_PATTERN",
    "GEGLU_PROVENANCE",
    "GEGLU_REGIONS",
    "GELU_ERF_PATTERN",
    "GELU_ERF_PROVENANCE",
    "GELU_REGIONS",
    "GELU_TANH_PATTERN",
    "GELU_TANH_PROVENANCE",
    "GQA_PATTERN",
    "GQA_REGIONS",
    "FUSED_GQA_SINK_FLASH2",
    "FUSED_GQA_SINK_FLASH3",
    "GQA_SINK_PATTERN",
    "GQA_SINK_REGIONS",
    "FUSED_MASKED_SOFTMAX_MEGATRON",
    "FUSED_MASKED_SOFTMAX_REFERENCE",
    "FUSED_MASKED_SOFTMAX_SINK",
    "FUSED_MASKED_SOFTMAX_TE",
    "FUSED_RMSNORM_HUB_MPS",
    "FUSED_RMSNORM_HUB_XPU",
    "FUSED_RMSNORM_LIGER",
    "FUSED_RMSNORM_REFERENCE",
    "FUSED_SOFTMAX_CUDA",
    "FUSED_SOFTMAX_REFERENCE",
    "FUSED_XIELU_CUDA",
    "FUSED_XIELU_REFERENCE",
    "MASKED_SOFTMAX_PATTERN",
    "MASKED_SOFTMAX_PROVENANCE",
    "MASKED_SOFTMAX_REGIONS",
    "MASKED_SOFTMAX_SINK_PATTERN",
    "FUSED_SOFTMAX_ONE_MEGATRON",
    "FUSED_SOFTMAX_ONE_REFERENCE",
    "SOFTMAX_ONE_PATTERN",
    "SOFTMAX_ONE_PROVENANCE",
    "SOFTMAX_ONE_REGIONS",
    "RELU_REGION",
    "RELU_REGIONS",
    "RELU_SAVED_INPUT",
    "FUSED_SILU_REGION",
    "RMSNORM_REGIONS",
    "SILU_REGIONS",
    "FUSED_SQUARED_RELU_REGION",
    "SQUARED_RELU_PATTERN",
    "SQUARED_RELU_REGIONS",
    "SOFTMAX_PATTERN",
    "SOFTMAX_PATTERN_SCALED",
    "SOFTMAX_PROVENANCE",
    "FUSED_SWIGLU_DECOMPOSED",
    "FUSED_SWIGLU_LIGER",
    "FUSED_SWIGLU_LIGER_FUSED_GATE_UP",
    "SWIGLU_PATTERN",
    "SWIGLU_PROVENANCE",
    "SWIGLU_REGIONS",
    "FUSED_SOFTPLUS",
    "FUSED_SOFTPLUS_SCALAR",
    "SOFTPLUS_PATTERN",
    "SOFTPLUS_PROVENANCE",
    "SOFTPLUS_REGIONS",
    "SOFTMAX_REGIONS",
    "XIELU_REGIONS",
    "FUSED_MAMBA2_MIXER_COMPOSED_TIER_A",
    "FUSED_MAMBA2_MIXER_DECODE",
    "FUSED_MAMBA2_MIXER_HUB_MEGA",
    "MAMBA2_MIXER_REGIONS",
    "ROPE_APPLY_REFERENCE",
    "ROPE_APPLY_REGIONS",
    "ROPE_MATERIALIZE_REFERENCE",
    "ROPE_MATERIALIZE_REGIONS",
]
