"""Fused linear + soft-cap + CE region implementations."""

from .rules import LINEAR_CE_SOFTCAP_PATTERN, LINEAR_CE_SOFTCAP_PROVENANCE
from .variants import (
    FUSED_LINEAR_CE_SOFTCAP_HUB_TRL,
    FUSED_LINEAR_CE_SOFTCAP_LIGER,
    FUSED_LINEAR_CE_SOFTCAP_REFERENCE,
    LINEAR_CE_SOFTCAP_REGIONS,
)

__all__ = [
    "FUSED_LINEAR_CE_SOFTCAP_HUB_TRL",
    "FUSED_LINEAR_CE_SOFTCAP_LIGER",
    "FUSED_LINEAR_CE_SOFTCAP_REFERENCE",
    "LINEAR_CE_SOFTCAP_PATTERN",
    "LINEAR_CE_SOFTCAP_PROVENANCE",
    "LINEAR_CE_SOFTCAP_REGIONS",
]
