"""GeGLU fused region implementations."""

from .rules import GEGLU_ERF_PATTERN, GEGLU_PATTERN, GEGLU_PROVENANCE
from .variants import (
    FUSED_GEGLU_DECOMPOSED,
    FUSED_GEGLU_DECOMPOSED_ERF,
    FUSED_GEGLU_LIGER,
    GEGLU_REGIONS,
)

__all__ = [
    "FUSED_GEGLU_DECOMPOSED",
    "FUSED_GEGLU_DECOMPOSED_ERF",
    "FUSED_GEGLU_LIGER",
    "GEGLU_ERF_PATTERN",
    "GEGLU_PATTERN",
    "GEGLU_PROVENANCE",
    "GEGLU_REGIONS",
]
