"""Fused depthwise causal conv1d region implementations."""

from .rules import DEPTHWISE_CAUSAL_CONV1D_PROVENANCE
from .variants import (
    FUSED_DEPTHWISE_CAUSAL_CONV1D_CUDA,
    FUSED_DEPTHWISE_CAUSAL_CONV1D_DECOMPOSED,
    FUSED_DEPTHWISE_CAUSAL_CONV1D_HUB,
    DEPTHWISE_CAUSAL_CONV1D_REGIONS,
)

__all__ = [
    "DEPTHWISE_CAUSAL_CONV1D_PROVENANCE",
    "DEPTHWISE_CAUSAL_CONV1D_REGIONS",
    "FUSED_DEPTHWISE_CAUSAL_CONV1D_CUDA",
    "FUSED_DEPTHWISE_CAUSAL_CONV1D_DECOMPOSED",
    "FUSED_DEPTHWISE_CAUSAL_CONV1D_HUB",
]
