"""Fused GatedGroupedRMSNorm region implementations."""

from .rules import (
    GATED_GROUPED_RMS_NORM_PATTERN,
    GATED_GROUPED_RMS_NORM_PROVENANCE,
)
from .variants import (
    FUSED_GATED_GROUPED_RMS_NORM_DEFAULT,
    FUSED_GATED_GROUPED_RMS_NORM_EAGER_HF,
    FUSED_GATED_GROUPED_RMS_NORM_REFERENCE,
    GATED_GROUPED_RMS_NORM_REGIONS,
)

__all__ = [
    "FUSED_GATED_GROUPED_RMS_NORM_DEFAULT",
    "FUSED_GATED_GROUPED_RMS_NORM_EAGER_HF",
    "FUSED_GATED_GROUPED_RMS_NORM_REFERENCE",
    "GATED_GROUPED_RMS_NORM_PATTERN",
    "GATED_GROUPED_RMS_NORM_PROVENANCE",
    "GATED_GROUPED_RMS_NORM_REGIONS",
]
