"""Lowering, estimation, and resource accounting."""

from .accounting import AccountingPolicy, PrecisionPolicy
from .lowered import LoweredEdge, LoweredGraph, LoweredNode
from .resolved import ResolvedValue
from .lowering.role import RoleContext, infer_accounting_role
from .lowering import (
    DEFAULT_REGISTRY,
    ImplementationDescriptor,
    ImplementationSelection,
    InvocationContext,
    LoweringError,
    LoweringRegistry,
    RegionImplementationDescriptor,
    RegionImplementationSelection,
    Region,
    discover_regions,
    lower,
    reference_invocation,
    select_implementation,
    select_region_implementation,
)
from .reports import (
    CostReport,
    FlopReport,
    HorizonCostReport,
    HorizonFlopReport,
    HorizonMemoryReport,
    MemoryReport,
)
from .memory import account_memory
from .flops import (
    FCM_OPERATION_FAMILIES,
    FlopCountingPolicy,
    account_fcm_flops,
    account_flops,
)
from .estimation import estimate, estimate_horizon
from .horizon import (
    ConvStateConfig,
    HorizonSimulation,
    HorizonSpec,
    HorizonStep,
    InputsFn,
    KVConfig,
    ModuleFn,
    RecurrentStateConfig,
    StepKind,
    decode_step,
    inputs_from_shape,
    inputs_from_token_ids,
    inputs_from_token_ids_and_labels,
    optimizer_step,
    simulate_horizon,
)
from .optimizer import AdamW, OptimizerPolicy, SGD, optimizer_update_flops
from .runtime import (
    CudaCublasWorkspacePolicy,
    NullRuntimeOverheadPolicy,
    RuntimeOverheadPolicy,
    cublas_workspace_bytes_per_handle,
    runtime_workspace_bytes,
)

__all__ = [
    "AccountingPolicy",
    "AdamW",
    "CostReport",
    "CudaCublasWorkspacePolicy",
    "cublas_workspace_bytes_per_handle",
    "DEFAULT_REGISTRY",
    "FlopReport",
    "HorizonCostReport",
    "HorizonFlopReport",
    "HorizonMemoryReport",
    "HorizonSimulation",
    "HorizonSpec",
    "HorizonStep",
    "InputsFn",
    "ConvStateConfig",
    "KVConfig",
    "ModuleFn",
    "RecurrentStateConfig",
    "StepKind",
    "decode_step",
    "optimizer_step",
    "ImplementationDescriptor",
    "ImplementationSelection",
    "InvocationContext",
    "LoweredEdge",
    "LoweredGraph",
    "LoweredNode",
    "LoweringError",
    "LoweringRegistry",
    "MemoryReport",
    "NullRuntimeOverheadPolicy",
    "OptimizerPolicy",
    "optimizer_update_flops",
    "PrecisionPolicy",
    "RegionImplementationDescriptor",
    "RegionImplementationSelection",
    "ResolvedValue",
    "RoleContext",
    "RuntimeOverheadPolicy",
    "Region",
    "SGD",
    "account_fcm_flops",
    "account_flops",
    "account_memory",
    "discover_regions",
    "FCM_OPERATION_FAMILIES",
    "FlopCountingPolicy",
    "estimate",
    "estimate_horizon",
    "infer_accounting_role",
    "lower",
    "reference_invocation",
    "runtime_workspace_bytes",
    "select_implementation",
    "select_region_implementation",
    "inputs_from_shape",
    "inputs_from_token_ids",
    "inputs_from_token_ids_and_labels",
    "simulate_horizon",
]
