"""Fused Mamba2Mixer block region implementations."""

from .rules import MAMBA2_MIXER_PATTERN, MAMBA2_MIXER_PROVENANCE
from .variants import (
    FUSED_MAMBA2_MIXER_COMPOSED_TIER_A,
    FUSED_MAMBA2_MIXER_DECODE,
    FUSED_MAMBA2_MIXER_HUB_MEGA,
    MAMBA2_MIXER_REGIONS,
)

__all__ = [
    "FUSED_MAMBA2_MIXER_COMPOSED_TIER_A",
    "FUSED_MAMBA2_MIXER_DECODE",
    "FUSED_MAMBA2_MIXER_HUB_MEGA",
    "MAMBA2_MIXER_PATTERN",
    "MAMBA2_MIXER_PROVENANCE",
    "MAMBA2_MIXER_REGIONS",
]
